baseURL = 'https://cassie.ink/'
languageCode = 'en-us'
title = 'cassie.ink'
theme = 'neverhungoveragain'

enableRobotsTXT = true

[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
  excludeFiles = ['templates/*.md']

[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'

[menus]
  [[menus.main]]
    name = '/about'
    pageRef = '/about'
    weight = 10
  [[menus.main]]
    name = '/archive'
    pageRef = '/archive'
    weight = 20
  [[menus.main]]
    name = '/books'
    pageRef = '/books'
    weight = 30

[markup.highlight]
    noClasses = false
    lineNos = true
    lineNumbersInTable = false

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 5
    ordered = false